### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by HighOnBuffs** [antimatter15/alpaca.cpp#30] opened 2023-03-17 17:17 UTC
![image](https://user-images.githubusercontent.com/51384219/225973997-c8d7b3c7-c855-4f93-b032-459c456da68c.png)
Tried windows install and get this behemoth of error when i  try to cmake --build . --config Release
Any idea why that is?

**Comment by sdwr** [comment] 2023-03-17 22:02
I'm guessing the compiler we're using has a problem with the "restrict" keyword on those lines.

**Comment by sdwr** [comment] 2023-03-17 22:52
Fixed by:

- installing the latest VS 2022 (don't think this mattered)
- running the CMake GUI in administrator
- navigating to the alpaca.cpp directory
- running "Configure" then "Generate" at the bottom in order

I think this rebuilt the CMake .txt files (?) to use the proper compiler

**Comment by Gerark** [comment] 2023-03-19 02:02
Had the same issue. I can confirm the problem is related to using an older version of Visual Studio. I changed from 19 to 22 and everything is fine now.

**Comment by ilazarte** [comment] 2023-03-21 03:26
Selected 22, latest version of cmake and everything works for me now.  Thanks!

**Closed** 2023-03-21 05:58 UTC
